version: '3.8'
services:
  geophoto:
    image: geophoto-map:latest
    ports:
      - "3000:3000"
    volumes:
      # 1. 核心数据卷（现在包含数据库与目录配置文件）
      - "./geophoto_data:/app/data"
      
      # 2. 缩略图缓存卷
      - "./geophoto_thumbs:/app/thumbnails"
      
      # 3. 您的照片共享文件夹（可以挂载多个）
      - "/volume1/homes/JamesBond/Photos/MobileBackup/iPhone:/app/nas_photos_3"
      - "/volume1/homes/JamesBond/Photos/MobileBackup/XQ-AS72/DCIM:/app/nas_photos_1"
      - "/volume1/homes/JamesBond/Photos/MobileBackup/V2241A/DCIM:/app/nas_photos_2"
      - "/volume1/homes/JamesBond/Photos/GoPro:/app/nas_photos_gopro"
      - "/volume1/homes/JamesBond/Drive/Moments/Mobile:/app/nas_photos_backup"
    restart: always